index:
  path: /
  controller: MainController::index

reserve_book:
  path: /reserve/{isbn}
  controller: MainController::reserveBook
  # methods: POST

unreserve_book:
  path: /unreserve/{isbn}
  controller: MainController::unreserveBook
  # methods: POST

