index:
  path: /
  controller: HelloController::redirect

hello_page:
  path: /hello/{name}
  controller: HelloController::index
  methods: GET
  defaults:
    name: default
  # options:
  #   middleware:
  #     - Form
  #     - Auth

hello_success:
  path: /hello/{name}
  controller: HelloController::success
  methods: POST
  defaults:
    name: default

login_form:
  path: /login
  controller: LoginController::GET
  methods: GET

login_auth:
  path: /login
  controller: LoginController::POST
  methods: POST

api:
  path: /api
  controller: ApiController::GET

test:
  path: /test
  controller: HelloController::test
  methods: GET

test_post:
  path: /test
  controller: HelloController::testPost
  methods: POST
