index:
  path: /
  controller: MainController::index
  options: [db, auth]

reserve_book:
  path: /reserve/{isbn}
  controller: BooksController::reserveBook
  methods: POST

unreserve_book:
  path: /unreserve/{isbn}
  controller: BooksController::unreserveBook
  methods: POST

