index:
  path: /
  controller: MainController::index

account:
  path: /account
  controller: MainController::account

reserve_book:
  path: /reserve/{isbn}
  controller: BooksController::reserveBook

unreserve_book:
  path: /unreserve/{isbn}
  controller: BooksController::unreserveBook
  methods: POST

login:
  path: /login
  controller: AuthController::login

sign_up:
  path: /signup
  controller: AuthController::signUp

log_out:
  path: /logout
  controller: AuthController::logOut